//autogenerated:yes
//nolint:revive,lll
package ros_model

import (
	"github.com/aler9/goroslib/pkg/msg"
)

type Sensors struct {
	msg.Package `ros:"custom_msg"`
	DeviceId    uint32
	Temperature float32
	LightLevel  uint32
	Smog        uint32
	Time        int64
}
