//autogenerated:yes
//nolint:revive,lll
package ros_model

import (
	"github.com/aler9/goroslib/pkg/msg"
)

type Sensors struct {
	msg.Package `ros:"custon_msg"`
	DeviceId    uint32
	Temperature float32
	No2         float32
	Co          float32
	Time        int64
}
